<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class GW_PayRevolut_Api
{
	
	function __construct($apikey, $sandbox=false) {
		$this->apikey = $apikey;
		$this->sandbox = $sandbox;
	}
	
	function request($method, $path, $data=[])
	{
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://'.($this->sandbox ? 'sandbox-' : '').'merchant.revolut.com/api/1.0/'.$path);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

		if($method=="POST"){
		    curl_setopt($ch, CURLOPT_POST, 1);

		    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
		}else{
		    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
		}

		$headers = array();
		//sk_sMGGQ_URIIY9Z3t-5P3h6-sc8Qt1AnH9Uz6ugl1RvIbQUxN02t6A5QcLy8aBEp1J
		$headers[] = "Authorization: Bearer {$this->apikey}";
		$headers[] = 'Content-Type: application/json; charset=utf-8';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		return json_decode($result, true);

	}

}