<?php

class GW_Location_Helper{
	
	static function expandData($item)
	{
		$data =  is_array($item->location_data) ? $item->location_data : json_decode($item->location_data, true);
		
		if (is_array($data)) {
			$item->location_country = $data['country_short'];
			$item->location_region = $data['region'];
			$item->location_subregion = $data['subregion'];
			$item->location_city = $data['city'];
			
			$item->lat = isset($data['lat']) ? $data['lat'] : '';
			$item->lng = isset($data['lng']) ? $data['lng'] : '';
			
			//d::dumpas([$this->lat, $this->lng]);
			//UPDATE myTable SET Coord = PointFromText(CONCAT('POINT(',myTable.DLong,' ',myTable.DLat,')'));
			//
			//https://www.marketingtechblog.com/calculate-distance/
			

			//GW_Country::singleton()->updateCountry($data['country_short'], $data['country']);
		}
	
	}
	
	static function locationQuery($q){
//$info = file_get_contents("https://nominatim.openstreetmap.org/search?format=json&q=vilnius");//. );
			
		
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://nominatim.openstreetmap.org/search?format=json&q='.rawurlencode($q));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Authority: nominatim.openstreetmap.org';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*\/*;q=0.8,application/signed-exchange;v=b3;q=0.7';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Cache-Control: max-age=0';
		$headers[] = 'Sec-Ch-Ua: \"Chromium\";v=\"118\", \"Google Chrome\";v=\"118\", \"Not=A?Brand\";v=\"99\"';
		$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
		$headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
		$headers[] = 'Sec-Fetch-Dest: document';
		$headers[] = 'Sec-Fetch-Mode: navigate';
		$headers[] = 'Sec-Fetch-Site: none';
		$headers[] = 'Sec-Fetch-User: ?1';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36';
		$headers[] = 'Referer: https://nominatim.openstreetmap.org/search?format=json&q='.rawurlencode($q);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		
		$list = json_decode($result);
		//d::dumpas($list);	
		return $list;
	}
	
	static function cityQuery($q){
//$info = file_get_contents("https://nominatim.openstreetmap.org/search?format=json&q=vilnius");//. );
			
		
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://nominatim.openstreetmap.org/search?format=jsonv2&city='.rawurlencode($q));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Authority: nominatim.openstreetmap.org';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*\/*;q=0.8,application/signed-exchange;v=b3;q=0.7';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Cache-Control: max-age=0';
		$headers[] = 'Sec-Ch-Ua: \"Chromium\";v=\"118\", \"Google Chrome\";v=\"118\", \"Not=A?Brand\";v=\"99\"';
		$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
		$headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
		$headers[] = 'Sec-Fetch-Dest: document';
		$headers[] = 'Sec-Fetch-Mode: navigate';
		$headers[] = 'Sec-Fetch-Site: none';
		$headers[] = 'Sec-Fetch-User: ?1';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36';
		$headers[] = 'Referer: https://nominatim.openstreetmap.org/search?format=jsonv2&city='.rawurlencode($q);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		
		$list = json_decode($result);
		//d::dumpas($list);	
		return $list;
	}
	
	//https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=243650685&class=highway&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json
	
	static function locationFromId($id, $rank_limit=99)
	{

		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $url='https://nominatim.openstreetmap.org/details.php?osmtype=R&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json&osmid='.$id);
		
		
		//d::dumpas($url);
		
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Authority: nominatim.openstreetmap.org';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Cache-Control: max-age=0';
		$headers[] = 'Sec-Ch-Ua: \"Chromium\";v=\"118\", \"Google Chrome\";v=\"118\", \"Not=A?Brand\";v=\"99\"';
		$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
		$headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
		$headers[] = 'Sec-Fetch-Dest: document';
		$headers[] = 'Sec-Fetch-Mode: navigate';
		$headers[] = 'Sec-Fetch-Site: none';
		$headers[] = 'Sec-Fetch-User: ?1';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36';
		//$headers[] = 'Referer: https://nominatim.openstreetmap.org/search?format=jsonv2&city='.rawurlencode($q);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		

		$result = json_decode($result);
		//echo json_encode($result, JSON_PRETTY_PRINT);''
		
		
		$display_name = [];
		
		foreach($result->address as $itm){
			if($itm->rank_address <= $rank_limit)
				$display_name[]=$itm->localname;
		}
		
		$result->display_name = implode(', ', $display_name);
		
		return $result;
	}
	
	function store($entry)
	{
		GW::db()->insert('gw_locations', $entry, false, true);
	}
	
	
/*
{
  "place_id": 153131690,
  "parent_place_id": 153515438,
  "osm_type": "W",
  "osm_id": 1165456642,
  "category": "highway",
  "type": "residential",
  "admin_level": 15,
  "localname": "Totorių g.",
  "names": {
    "name": "Totorių g.",
    "name:be": "Татарская вуліца",
    "name:lt": "Totorių g.",
    "name:pl": "ulica Tatarska",
    "name:tt": "Татар урамы",
    "name:crh": "Tatar soqaği"
  },
  "addresstags": {},
  "calculated_postcode": "01121",
  "country_code": "lt",
  "indexed_date": "2023-09-05T07:36:45.013235+00:00",
  "importance": 0.10000999999999993,
  "calculated_importance": 0.10000999999999993,
  "extratags": {
    "lit": "yes",
    "width": "8",
    "surface": "asphalt",
    "maxspeed": "40",
    "sidewalk": "both",
    "wikidata": "Q28669444",
    "parking:left": "street_side",
    "lane_markings": "no",
    "parking:right": "no",
    "sidewalk:both:surface": "paving_stones",
    "parking:left:orientation": "parallel"
  },
  "rank_address": 26,
  "rank_search": 26,
  "isarea": false,
  "centroid": {
    "type": "Point",
    "coordinates": [
      25.282218,
      54.6856126
    ]
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      25.282218,
      54.6856126
    ]
  },
  "address": [
    {
      "localname": "Totorių g.",
      "place_id": 153131690,
      "osm_id": 1165456642,
      "osm_type": "W",
      "class": "highway",
      "type": "residential",
      "admin_level": 15,
      "rank_address": 26,
      "distance": 0,
      "isaddress": true
    },
    {
      "localname": "Paupys",
      "place_id": 153156639,
      "osm_id": 9592894334,
      "osm_type": "N",
      "class": "place",
      "type": "suburb",
      "admin_level": 15,
      "rank_address": 22,
      "distance": 0.02153780562383436,
      "isaddress": false
    },
    {
      "localname": "Užupis",
      "place_id": 153381817,
      "osm_id": 32872718,
      "osm_type": "N",
      "class": "place",
      "type": "suburb",
      "admin_level": 15,
      "rank_address": 22,
      "distance": 0.016888462201161285,
      "isaddress": false
    },
    {
      "localname": "Old Town",
      "place_id": 153515438,
      "osm_id": 273185391,
      "osm_type": "N",
      "class": "place",
      "type": "suburb",
      "admin_level": 15,
      "rank_address": 22,
      "distance": 0.007105635147544857,
      "isaddress": true
    },
    {
      "localname": "Senamiesčio seniūnija",
      "place_id": 153240869,
      "osm_id": 968951,
      "osm_type": "R",
      "class": "boundary",
      "type": "administrative",
      "admin_level": 10,
      "rank_address": 20,
      "distance": 1.2114625288560315e-7,
      "isaddress": true
    },
    {
      "localname": "Vilnius",
      "place_id": 153262495,
      "osm_id": 1529146,
      "osm_type": "R",
      "class": "boundary",
      "type": "administrative",
      "admin_level": 8,
      "rank_address": 16,
      "distance": 1.1434497146818515e-8,
      "isaddress": true
    },
    {
      "localname": "Vilnius city municipality",
      "place_id": 153193418,
      "osm_id": 968952,
      "osm_type": "R",
      "class": "boundary",
      "type": "administrative",
      "admin_level": 5,
      "rank_address": 10,
      "distance": 4.238912337361556e-7,
      "isaddress": true
    },
    {
      "localname": "Vilnius County",
      "place_id": 153363396,
      "osm_id": 977317,
      "osm_type": "R",
      "class": "boundary",
      "type": "administrative",
      "admin_level": 4,
      "rank_address": 8,
      "distance": 0.0000014042161332341275,
      "isaddress": true
    },
    {
      "localname": "01121",
      "class": "place",
      "type": "postcode",
      "rank_address": 5,
      "distance": 0,
      "isaddress": true
    },
    {
      "localname": "lt",
      "class": "place",
      "type": "country_code",
      "rank_address": 4,
      "distance": 0,
      "isaddress": false
    },
    {
      "localname": "Lithuania",
      "class": "place",
      "type": "country",
      "rank_address": 4,
      "distance": 0,
      "isaddress": true
    }
  ]
}
 *  */	
}

