CREATE TABLE IF NOT EXISTS `gw_expenses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL DEFAULT 0,
  `source_id` int(11) NOT NULL DEFAULT 0,
  `expense_date` date DEFAULT NULL,
  `expense_month` varchar(7) DEFAULT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `amount` decimal(12,2) DEFAULT NULL,
  `type` varchar(32) NOT NULL DEFAULT 'other',
  `coefficient` decimal(12,6) NOT NULL DEFAULT '1.000000',
  `child_amount` decimal(12,2) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'processing',
  `note` text DEFAULT NULL,
  `extra` mediumtext DEFAULT NULL,
  `api_response` mediumtext DEFAULT NULL,
  `processed_time` datetime DEFAULT NULL,
  `insert_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`),
  KEY `source_id` (`source_id`),
  KEY `expense_month` (`expense_month`),
  KEY `expense_date` (`expense_date`),
  KEY `type` (`type`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
